name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Instancia a la que desplegar'
        type: choice
        options: [bar777, arca]
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    uses: nextup-py/deploy-actions/.github/workflows/laravel-deploy.yml@main
    with:
      run_tests: true
      run_migrations: true
    secrets: inherit
